language: go

branches:
  only:
    - master

before_script:
  - go vet ./...

services:
  - docker

install:
  - go get -u golang.org/x/lint/golint

script:
  - GOOS_VAL=$(shell go env GOOS) GOARCH_VAL=$(shell go env GOARCH) go build -v -a -installsuffix cgo -o ./build/weather-forecast cmd/*.go
  - docker build . -t weather-forecast:master
  - docker login $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
  - docker push wesleyfreitas472/weather-forecast:master
