language: go

go:
  - "1.12"

branches:
  only:
    - master

services:
  - docker

install:
  - export TRAVIS_BUILD_DIR=$GOPATH/src/WesleyFreitas472/go-weather-forecast
  - go get -u golang.org/x/lint/golint

script:
  - go build -v -a -installsuffix cgo -o ./build/weather-forecast cmd/*.go
  - docker build . -t weather-forecast:master
  - docker login $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
  - docker push wesleyfreitas472/weather-forecast:master
